# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='address',
            field=models.TextField(null=True, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Company Name', max_length=100, verbose_name='Company name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myprofile',
            name='mobile_number',
            field=models.CharField(default=919902438541, help_text='+CountryCode-PhoneNo', max_length=100, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myprofile',
            name='phone_number',
            field=models.CharField(default=919902438541, help_text='+CountryCode-PhoneNo', max_length=100, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myprofile',
            name='type_of_business',
            field=models.CharField(default='Software', help_text='Logistics Company, School, Hospital', max_length=200, verbose_name='Business Or Institution Type'),
            preserve_default=False,
        ),
    ]
